# Generated by Django 3.0.6 on 2020-05-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200517_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
