# Generated by Django 3.0.6 on 2020-05-17 18:21

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200517_1804'),
        ('main', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='student_attendees', to='users.Student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=main.models.one_hour_ahead),
        ),
        migrations.AlterField(
            model_name='event',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_leader', to='users.Staff'),
        ),
    ]
