# Generated by Django 3.0.6 on 2020-05-18 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200518_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auth_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
