# Generated by Django 3.0.6 on 2020-05-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_auth_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='mark_attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
