# Generated by Django 3.0.6 on 2020-05-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200519_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='auth_hash',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
