# Generated by Django 3.0.6 on 2020-05-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_attendance_auth_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='verification_time',
            field=models.DateTimeField(null=True),
        ),
    ]
