# Generated by Django 3.0.6 on 2020-05-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200517_1804'),
        ('main', '0014_verification_verification_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='staff',
        ),
        migrations.AlterField(
            model_name='verification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
