# Generated by Django 3.0.6 on 2020-05-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_verification_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='register_taken',
            field=models.BooleanField(default=False),
        ),
    ]
