# Generated by Django 3.0.6 on 2020-05-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_event_register_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
    ]
