# Generated by Django 3.0.6 on 2020-05-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main', '0002_auto_20200517_1207'),
        ('users', '0002_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
