# Generated by Django 3.0.6 on 2020-05-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200517_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Students'},
        ),
    ]
