# Generated by Django 3.0.6 on 2020-05-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main', '0004_auto_20200517_1342'),
        ('users', '0008_student_blah'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
