# Generated by Django 3.0.6 on 2020-05-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
