# Generated by Django 3.0.6 on 2020-05-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200517_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
